//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyLoanApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int ApplicationNumber { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string CustomerName { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Age { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string SelectedLoanType { get; set; }
        public decimal RequiredLoanAmount { get; set; }
        public double RateOfInterest { get; set; }
        public int LoanTenure { get; set; }
        public decimal LoanEMI { get; set; }
        public decimal SanctionedAmount { get; set; }
        public int SanctionedTenure { get; set; }
        public double SanctionedInterestRate { get; set; }
        public double SanctionedEMI { get; set; }
        public string LoanStatus { get; set; }
        public string RejectionRemark { get; set; }
    }
}
