//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyLoanApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanType
    {
        public string LoanCode { get; set; }
        public string LoanDescription { get; set; }
        public double LoanInterestRatePerAnnum { get; set; }
        public decimal MinimumLoanAmount { get; set; }
        public decimal MaximumLoanAmount { get; set; }
        public int MinimumAgeRequired { get; set; }
        public int MaxmimAgeRequired { get; set; }
    }
}
