//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyLoanApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserMVC
    {
        public int Id { get; set; }

        [DisplayName("Enter your Name:")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Name { get; set; }


        [DisplayName("Enter your Email Id:")]
        [Required(ErrorMessage = "This Field is Required")]
        public string EmailId { get; set; }


        [DisplayName("Select Gender:")]

        [Required(ErrorMessage = "This Field is Required")]
        public char Gender { get; set; }
        [DataType(DataType.Date)]


        [DisplayName("Enter BirthDate:")]
        [Required(ErrorMessage = "This Field is Required")]
        public string DOB { get; set; }


        [DisplayName("Enter your City:")]
        [Required(ErrorMessage = "This Field is Required")]
        public string City { get; set; }

        [DisplayName("Enter your Password:")]
        [StringLength(100, ErrorMessage = "Password must have currect character", MinimumLength = 8)]
        [RegularExpression(@"^([a-zA-Z0-9@*#]{8,15})$", ErrorMessage = "Password must contain: " +
            "Minimum 8 characters atleast 1 UpperCase Alphabet, 1 LowerCase Alphabet," +
            " 1 Number and 1 Special Character")]
        [Required(ErrorMessage = "This Field is Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Enter your Re-Password:")]
        [Required(ErrorMessage = "Please enter confirm password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]

        public string RePassword { get; set; }
    }
}
